# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_point', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=6)),
            ],
            options={
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='companystats.Company'),
        ),
        migrations.AddField(
            model_name='billing',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='companystats.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set([('company', 'department', 'expenditure_point')]),
        ),
    ]
